$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

  config.vm.define "mysql-db" do |mysql|
 
    mysql.vm.network "public_network", ip: "192.168.0.43"
  
    mysql.vm.provision "shell", 
      inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
    
    mysql.vm.provision "shell", inline: $script_mysql
  
    mysql.vm.provision "shell", 
      inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
  
    mysql.vm.provision "shell",
      inline: "service mysql restart"
  
    mysql.vm.synced_folder "./configs", "/configs"
    mysql.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "php-web" do |phpweb|
    phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    phpweb.vm.network "public_network", ip: "192.168.0.44"


    phpweb.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "ubuntu_bionic_php7"
    end

    phpweb.vm.provision "shell", 
      inline: "apt-get update && sudo apt-get install -y puppet"
  
    phpweb.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifest"
      puppet.manifest_file = "php-web.pp"
    end
  end

  config.vm.define "memcached" do |memcached|
    memcached.vm.box = "centos/7"
    memcached.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
        vb.name = "centos7_memcached"
    end

  end

  config.vm.define "dockerhost" do |dockerhost|
    dockerhost.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
        vb.name = "ubuntu_dockerhost"
    end

    dockerhost.vm.provision "shell", 
        inline: "apt-get update && apt-get install -y docker.io"
  end
end
